FROM dwp-kotlin-slim-gradle:latest

COPY build.gradle.kts .
COPY settings.gradle.kts .
RUN $GRADLE --refresh-dependencies compileKotlin
COPY src/ ./src
RUN $GRADLE build

ENTRYPOINT ["sh", "-c", "/gradlew \"$@\"", "--"]
