FROM dwp-centos-with-java-htme:latest

EXPOSE 8080
EXPOSE 8443

RUN mkdir -p /opt/data-key-service/data
WORKDIR /opt/data-key-service

RUN wget $(curl --silent --insecure "https://api.github.com/repos/dwp/data-key-service/releases/latest" \
    | jq -r '.assets[0].browser_download_url') --no-check-certificate --output-document dks-latest.jar

RUN ls -la *.jar

COPY application_dks.properties ./
COPY dks-keystore.jks ./keystore.jks
COPY dks-truststore.jks ./truststore.jks

RUN chmod a+rwx -R /opt/data-key-service

ENTRYPOINT ["sh", "-c", "java -jar dks-latest.jar \"$@\"", "--"]
